/*==================================================
SFAX MEDINA HERITAGE
كشف بياني حول العقارات المتداعية للسقوط والبنايات المهملة (أوت 2018)
جمعية صيانة المدينة العتيقة بصفاقس

⚠️ ملاحظة هامة:
تم استخراج بيانات هذا الملف (المالك عنوان العقار نوع العقار تشخيص
الاختلالات والتدخل المقترح) آليا من مسح ضوئي لوثيقة مكتوبة بخط اليد.
جميع الحقول معلّمة بـ verified:false ويجب مراجعتها ومقارنتها بالوثيقة
الأصلية قبل اعتمادها بشكل نهائي، خاصة حقل "المالك" لأنه معطى حساس
يخص أشخاصا حقيقيين ومكتوب بخط اليد وقد يحتمل قراءات مختلفة.

الأرقام من 211 إلى 220 غير موجودة في الكشف البياني الأصلي (فجوة
بالترقيم بين العقار 210 والعقار 221) وتظهر بذلك بدون بيانات.

استعمل نموذج الإدارة (زر "وضع الإدارة" أسفل الخريطة) لتصحيح أو
تأكيد أي بيانات هنا بعد مراجعتها من الوثيقة الأصلية.
==================================================*/

const atriskBuildingsData = [

{ id:1,  owner:"ورثة رشيد بلحاج (بالبيع)", address:"نهج ازنريطل عدد 27 / نهج برج النار عدد 4+2", type:"سكن + طابق علوي", diagnosis:"تشققات وتصدعات خطيرة بالجدران والسقوف، جزء من السقف آيل للسقوط بالواجهة العلوية", intervention:"هدم العقار (الطابق العلوي) وترميم قبل تدهور الحالة", risk:"Red", verified:false },
{ id:2,  owner:"ورثة رشيد بلحاج (بالبيع)", address:"نهج برج النار عدد 29+31", type:"سفلي + طابق علوي", diagnosis:"تصدعات ونشقاقات خطيرة، تهدم جزئي بالسقف", intervention:"هدم الطابق العلوي وترميم قبل السقوط", risk:"Red", verified:false },
{ id:3,  owner:"خالد ورفيق بن محمد", address:"نهج برج النار عدد 33", type:"طابق أول + طابق ثاني", diagnosis:"عوارض الطابق العلوي حديدية ومتآكلة", intervention:"ترميم الطابق العلوي وتدعيم قبل السقوط", risk:"Orange", verified:false },
{ id:4,  owner:"ورثة سالم عبد الكريم بوعزيزي", address:"نهج برج النار عدد 52 / عدد 54", type:"طابق علوي", diagnosis:"تصدعات خطيرة بالجدران، السقف من الفوق مائل", intervention:"هدم الطابق العلوي وترميم قبل السقوط", risk:"Red", verified:false },
{ id:5,  owner:"—", address:"نهج برج النار عدد 74", type:"طابق أول + طابق ثاني", diagnosis:"تصدعات بالبناء وحالة سيئة", intervention:"هدم العقار بالكامل", risk:"Red", verified:false },
{ id:6,  owner:"عبد الرزاق الشريف", address:"نهج دار السبعي زنقة عدد 25 / عدد 11", type:"طابق علوي", diagnosis:"شقوق عميقة، سقوط أجزاء من الحائط", intervention:"إعادة بناء الطابق العلوي وترميم الشبكات", risk:"Red", verified:false },
{ id:7,  owner:"نصيرة بالي ورثة الديماسي", address:"نهج دار السبعي عدد 13+9 (مكرر)", type:"معمل حلويات", diagnosis:"تصدعات وتشققات خطيرة بالجدران", intervention:"هدم الطابق العلوي بالكامل وترميم قبل السقوط", risk:"Red", verified:false },
{ id:8,  owner:"ورثة التمصمصي", address:"نهج سعد خريز زنقة 3 عدد 5 / عدد 1", type:"سفلي + طابق علوي", diagnosis:"سقوف مهترئة وشقوق بالجدران بسبب تسرب المياه", intervention:"ترميم الطابق العلوي وترميم قبل السقوط", risk:"Orange", verified:false },
{ id:9,  owner:"ورثة صالح نجاح", address:"نهج دار السبعي زنقة عدد 24", type:"طابق علوي", diagnosis:"تصدعات خطيرة بالجدران", intervention:"هدم الطابق العلوي وترميم قبل السقوط", risk:"Red", verified:false },
{ id:10,  owner:"محمد علي الصافي", address:"نهج دار السبعي عدد 30+28", type:"طابق علوي", diagnosis:"تصدعات خطيرة وجزء من السقوف متهدم", intervention:"هدم الطابق العلوي وترميم", risk:"Red", verified:false },
{ id:11,  owner:"—", address:"نهج السبعي عدد 35+37", type:"دكان + طابق علوي بطابقين ارضي", diagnosis:"عقار متصدع ومتشقق ومكناس بالجدران، حالة سيئة", intervention:"هدم الطابق العلوي وترميم", risk:"Red", verified:false },
{ id:12,  owner:"ورثة قريبعة", address:"نهج دار السبعي عدد 57-51 و 63-61", type:"دكان + عدد 2 طابق علوي", diagnosis:"تشققات خطيرة ومناطق بالجدران آيلة للسقوط", intervention:"هدم الطابق العلوي وتدعيم وترميم", risk:"Red", verified:false },
{ id:13,  owner:"ورثة قريبعة", address:"نهج دار السبعي عدد 44", type:"طابق علوي", diagnosis:"تصدعات وتشققات عميقة بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:14,  owner:"محمود الحضيرة", address:"نهج دار السبعي عدد 80", type:"طابق علوي", diagnosis:"تصدعات ومناطق خطيرة بالجدران", intervention:"هدم العقار بالكامل", risk:"Red", verified:false },
{ id:15,  owner:"—", address:"نهج دار السبعي عدد 86", type:"أرضي + طابق علوي", diagnosis:"العقار مغلق، تصدعات ومناطق للفصلات وحالة سيئة", intervention:"ترميم الطابق العلوي وترميم قبل السقوط", risk:"Orange", verified:false },
{ id:16,  owner:"—", address:"نهج دار السبعي عدد 92", type:"طابق علوي", diagnosis:"العقار مغلق، تصدعات وتشققات بالجدران وحالة سيئة", intervention:"هدم الطابق العلوي وترميم", risk:"Red", verified:false },
{ id:17,  owner:"—", address:"نهج دار السبعي عدد 95", type:"طابق علوي", diagnosis:"العقار مغلق، تصدعات وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:18,  owner:"ورثة الوكيل", address:"نهج دار السبعي عدد 66 / مكرر", type:"طابق علوي", diagnosis:"العقار مغلق، تصدعات ومكناسي للسقوط", intervention:"ترميم قبل السقوط بالكامل", risk:"Orange", verified:false },
{ id:19,  owner:"نور الدين عزو", address:"نهج دار السبعي عدد 51 (ورشة صناعة الأحذية)", type:"طابق علوي", diagnosis:"العقار مسكونة، شققات وتصدعات عميقة بالجدران وحالة البناء سيئة", intervention:"ترميم الطابق الثاني ورفع الاختصاص", risk:"Orange", verified:false },
{ id:20,  owner:"عبد الجليل العبادي", address:"نهج دار السبعي زنقة 21 عدد 9 / عدد 90", type:"طابق أرضي + طابق علوي", diagnosis:"العقار محل سكني وتشققات وتصدعات بالجدران، حالة سيئة", intervention:"ترميم قبل السقوط وحماية الواجهة", risk:"Orange", verified:false },
{ id:21,  owner:"ورثة سالم المصمودي", address:"نهج دار السبعي زنقة 21 عدد 9", type:"طابق أرضي + طابق علوي", diagnosis:"العقار مغلق، تشققات وتصدعات بالجدران وحالة سيئة", intervention:"هدم غير قبل للنقاط وتنظيف بناء الطابق", risk:"Red", verified:false },
{ id:22,  owner:"عادل الزواوي", address:"نهج دار السبعي زنقة 21 عدد 11", type:"طابق علوي", diagnosis:"تصدعات خطيرة وحالة السقوف منهارة", intervention:"هدم الطابق الثاني وترميم", risk:"Red", verified:false },
{ id:23,  owner:"ورثة حسني", address:"نهج السبعي عدد 3+3 مكرر", type:"مقهى + عدد 2 دكاكين", diagnosis:"القارين مغلقان، شققات ووجود مصعدة للعقار حجرة جزئية من السقف الغصء والفتحات", intervention:"ترميم جدار جزئي وحيك البنابة الاحدية", risk:"Orange", verified:false },
{ id:24,  owner:"ورثة المصمودي", address:"نهج السور عدد 62", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة بناء سيئة", intervention:"ترميم بجدران للتقص", risk:"Orange", verified:false },
{ id:25,  owner:"العلوي", address:"نهج السور عدد 67", type:"طابق علوي", diagnosis:"تصدعات وتشققات عميقة بالجدران والراجعة", intervention:"ترميم قبل للتقص", risk:"Orange", verified:false },
{ id:26,  owner:"الوكيل", address:"نهج السور عدد 73", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:27,  owner:"ورثة العنتري", address:"نهج سيدي سعيد خنفير عدد 160 مكرر", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:28,  owner:"—", address:"نهج سيدي سعيد خنفير عدد 3", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:29,  owner:"—", address:"نهج سيدي سعيد خنفير عدد 6", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:30,  owner:"ورثة الصادق عشير عثمان", address:"نهج سيدي سعيد خنفير زنقة 52 عدد 6+12", type:"طابق أرضي + طابق علوي + مطابق", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:31,  owner:"—", address:"نهج ازنريطل عدد 26", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:32,  owner:"—", address:"نهج السمراء عدد 4", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:33,  owner:"توفيق الترمي", address:"نهج السمراء زنقة 1 عدد 12", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:34,  owner:"—", address:"نهج علي عبد الناضر عدد 4+6 مكرر", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:35,  owner:"—", address:"نهج الخلفية عدد 30 مكرر", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:36,  owner:"—", address:"نهج الخلفية عدد 49-51-53", type:"دكان + طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:37,  owner:"عبد الوهاب النيازل", address:"نهج شرورة عدد 1", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:38,  owner:"سنة الجمل", address:"نهج شرورة عدد 3", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:39,  owner:"حظار اللوز", address:"نهج شرورة عدد 5", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:40,  owner:"—", address:"نهج شرورة عدد 33", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:41,  owner:"سنوى الدريس", address:"نهج الدريبة عدد 76", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:42,  owner:"ناجح خير الله", address:"نهج الدريبة عدد 106-108-110", type:"دكان + طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:43,  owner:"—", address:"نهج جاكرتة عدد 28 (محل سكني)", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:44,  owner:"—", address:"نهج جاكرتة عدد 33", type:"دكان", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:45,  owner:"عبد العزيز سعد الله", address:"نهج جاكرتة عدد 35", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:46,  owner:"ملك بلحاج", address:"نهج جاكرتة عدد 34 (محل سكني)", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:47,  owner:"ورثة محمد بوحامد", address:"نهج سيدي علي النوري عدد 19", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:48,  owner:"ورثة السالمي", address:"نهج سيدي علي النوري عدد 20-22", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:49,  owner:"—", address:"سباط نهج سيدي علي النوري", type:"سباط", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:50,  owner:"بن سالم", address:"نهج سيدي خليل عدد 37", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:51,  owner:"—", address:"نهج سيدي خليل عدد 39", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:52,  owner:"ورثة محمد الخز الإلبي", address:"نهج سيدي خليل عدد 43", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:53,  owner:"—", address:"نهج سيدي خليل عدد 49", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:54,  owner:"ورثة بوزيد", address:"نهج سيدي خليل عدد 66", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:55,  owner:"عبد السلام خليفة", address:"نهج أحمد باي زنقة 55 عدد 16", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:56,  owner:"—", address:"نهج سيدي جبلة زنقة 26 عدد 8+8", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:57,  owner:"ورثة الشرقي", address:"نهج العيساوية عدد 9+11", type:"مطبعة + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:58,  owner:"ملك الدولة", address:"جامع سيدي سعادة كاتون / نهج العيساوية عدد 16", type:"جامع (معلم ديني)", diagnosis:"معلم ديني (جامع)، بحاجة إلى صيانة دورية", intervention:"متابعة الصيانة الدورية للمعلم", risk:"Orange", verified:false },
{ id:59,  owner:"ورثة القفوري", address:"نهج خير الدين عدد 31", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:60,  owner:"البشير عبيد", address:"نهج خير الدين عدد 35", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:61,  owner:"مراد القروي", address:"نهج خير الدين عدد 39", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:62,  owner:"ورثة محمد كمال", address:"نهج خير الدين عدد 41", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:63,  owner:"الطواطي", address:"نهج خير الدين عدد 51", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:64,  owner:"ورثة العش", address:"نهج الطاهر المنيف عدد 14", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:65,  owner:"بوبكر الفلال", address:"نهج الطاهر المنيف عدد 13+15", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:66,  owner:"ورثة البيناتي", address:"نهج الحميدية عدد 13", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:67,  owner:"طارق الكراي", address:"نهج الحميدية عدد 31", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:68,  owner:"ورثة الفارسي", address:"نهج الحميدية عدد 11", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:69,  owner:"فتحية غربال", address:"نهج عبد العزيز الفراتي عدد 27", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:70,  owner:"—", address:"سباط نهج القائد عدد 7", type:"طابق علوي + سباط", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:71,  owner:"—", address:"سباط نهج القائد عدد 7", type:"طابق علوي + سباط", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:72,  owner:"فاخر الغراب", address:"نهج المنجي سليم عدد 32", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:73,  owner:"حبيب الفرنسي", address:"نهج المنجي سليم عدد 57", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:74,  owner:"أمال كنيش", address:"ركن نهج المنجي سليم عدد 50", type:"مصلى سيدي منصور", diagnosis:"مصلى ديني، حالة عامة تحتاج متابعة", intervention:"ترميم وصيانة المصلى", risk:"Orange", verified:false },
{ id:75,  owner:"—", address:"نهج البساوية عدد 1", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:76,  owner:"—", address:"سباط نهج المنجي سليم عدد 98", type:"سباط", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:77,  owner:"ورثة بوعصيدة", address:"نهج المنجي سليم عدد 134", type:"حمام سيدي المسندي", diagnosis:"حمام تاريخي (سيدي المسندي)، تصدعات بالجدران والقبة الجوفية", intervention:"ترميم الحمام والسطح، حماية النمط التقليدي", risk:"Orange", verified:false },
{ id:78,  owner:"—", address:"نهج المنجي سليم قصارية الجمل عدد 7 مكرر", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:79,  owner:"زهرة العبادي", address:"نهج المنجي سليم قصارية الجمل عدد 7", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:80,  owner:"—", address:"نهج المنجي سليم قصارية الجمل عدد 7", type:"مسمى خشبي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:81,  owner:"الطاهر الحوة", address:"نهج المنجي سليم زنقة 16 عدد 1 مكرر", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:82,  owner:"—", address:"نهج المنجي سليم زنقة 16 عدد 14 مكرر", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:83,  owner:"المنجي الشرفي", address:"نهج المنجي سليم زنقة 16 عدد 20 مكرر", type:"المسمى الخشبي والدرابزين", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:84,  owner:"—", address:"نهج المنجي سليم زنقة 16 عدد 1 مكرر", type:"غرفة لصناعة الأحذية", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:85,  owner:"حميدة غراب", address:"نهج المنجي سليم قصارية الشيشمة عدد 13", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:86,  owner:"—", address:"نهج المنجي سليم قصارية الشيشمة عدد 9", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:87,  owner:"عبد العزيز كمون", address:"نهج المنجي سليم قصارية الشيشمة عدد 7", type:"مصنع خشبي والدرابزين", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:88,  owner:"—", address:"نهج المنجي سليم قصارية الشيشمة عدد 3", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:89,  owner:"ورثة الغنقي", address:"نهج المنجي سليم قصارية القنيقة عدد 3", type:"دكان", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:90,  owner:"—", address:"نهج المنجي سليم قصارية القنيقة عدد 5", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:91,  owner:"ملك بلدي", address:"نهج المنجي سليم عدد 139", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:92,  owner:"بن مسعود", address:"نهج المنجي سليم عدد 141", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:93,  owner:"محمد غربال", address:"نهج المنجي سليم عدد 167", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:94,  owner:"الحنينة", address:"سوق العطارين قصارية الربيع زنقة 1 عدد 21", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:95,  owner:"—", address:"نهج الجامع الكبير عدد 52 (مكتبة)", type:"طابق أول + طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:96,  owner:"جمعية المحافظة على القرآن الكريم والأخلاق (الفن)", address:"نهج حزون عدد 11 / 35 / 37", type:"طابق أرضي + طابق علوي", diagnosis:"العقار محل نشاط جمعوي، تصدعات وتشققات جزئية", intervention:"ترميم قبل تدهور الحالة", risk:"Orange", verified:false },
{ id:97,  owner:"محمد بن جماعة", address:"نهج حزون عدد 4+6", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:98,  owner:"ورثة عامر البيناتي", address:"نهج مكة عدد 9", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:99,  owner:"—", address:"نهج مكة عدد 9", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:100,  owner:"التوروي كمال", address:"نهج مكة زنقة 48 عدد 4", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:101,  owner:"الجربي", address:"نهج مكة زنقة 48 عدد 6", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:102,  owner:"ملك بلدي", address:"نهج مكة عدد 14", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:103,  owner:"عيبة", address:"نهج مكة عدد 82", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:104,  owner:"ورثة الخراط", address:"نهج مكة عدد 89", type:"ساحة مسيجة", diagnosis:"العقار أصبح ساحة مسيجة ومصبا للفضلات، جدران متبقية آيلة للسقوط", intervention:"رفع الأنقاض وتنظيف الفضاء، ترميم الجدران المتبقية أو هدمها", risk:"Red", verified:false },
{ id:105,  owner:"عبد العزيز هتاتة", address:"نهج مكة عدد 132", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:106,  owner:"ملك بلدي + خاص", address:"سوق الأطعمة", type:"طابق أرضي + طابق علوي", diagnosis:"سوق الأطعمة، تشققات وتصدعات بالجدران وحالة السقوف سيئة", intervention:"ترميم قبل السقوط ومراجعة شبكات البنية التحتية", risk:"Orange", verified:false },
{ id:107,  owner:"ملك بلدي", address:"نهج الصباغين قصارية أمين عدد 7", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:108,  owner:"ملك بلدي", address:"نهج الصباغين قصارية أمين عدد 9", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:109,  owner:"رشيد عبيد", address:"نهج الصباغين قصارية أمين عدد 13", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:110,  owner:"ملك بلدي", address:"نهج الصباغين قصارية أمين عدد 15", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:111,  owner:"خليفة العموص", address:"نهج الصباغين قصارية أمين عدد 17", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:112,  owner:"سانية العموص", address:"نهج الصباغين قصارية أمين عدد 19", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:113,  owner:"ملك بلدي", address:"نهج الصباغين قصارية أمين عدد 25", type:"غرفة", diagnosis:"غرفة ملحقة بمجمع سكني/حرفي، حالة بناء متوسطة إلى سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:114,  owner:"عبد السلام الشعبوني", address:"نهج الشيخ السلامي عدد 9", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:115,  owner:"محمد اللوز", address:"نهج الثنية السلامي عدد 10", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:116,  owner:"—", address:"نهج باب الجديد زنقة عدد 4", type:"طابق علوي + طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:117,  owner:"—", address:"نهج باب الجديد عدد 16", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:118,  owner:"—", address:"نهج باب الجديد عدد 20", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:119,  owner:"محمد الزرواوي", address:"نهج باب الجديد عدد 26", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:120,  owner:"—", address:"نهج باب الجديد عدد 32", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:121,  owner:"—", address:"نهج باب الجديد عدد 25", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:122,  owner:"—", address:"نهج باب الجديد عدد 56", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:123,  owner:"—", address:"نهج باب الجديد زنقة 63 عدد 2-4-5-7-9-11-13", type:"دكان + طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:124,  owner:"—", address:"نهج باب الجديد عدد 43 مكرر", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:125,  owner:"سليم العفاس", address:"نهج باب الجديد عدد 47", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:126,  owner:"ورثة العبادي", address:"نهج باب الجديد عدد 65", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:127,  owner:"إسماعيل بن أحمد", address:"نهج سالم البكري عدد 1", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:128,  owner:"ميت كمكاس + ورثة السدي", address:"نهج سالم البكري عدد 7", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:129,  owner:"ورثة الزريعي", address:"نهج سالم البكري عدد 9", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:130,  owner:"ورثة عمر المصراتي", address:"نهج علي الترخي عدد 4", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:131,  owner:"فوزي كمودة", address:"نهج علي الترخي عدد 10", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:132,  owner:"ورثة الصادق العلوي", address:"نهج علي الترخي عدد 24", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:133,  owner:"—", address:"سباط الرومي، نهج باب الجديد الجديد عدد 48 (21+19+17)", type:"ساحة مسيجة", diagnosis:"ساحة مسيجة نتجت عن هدم عقارات سابقة، تراكم أنقاض ونفايات", intervention:"رفع الأنقاض وتنظيف الفضاء وإعادة تهيئته", risk:"Orange", verified:false },
{ id:134,  owner:"بالقاسم القيثوري", address:"نهج المرابطين عدد 13", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:135,  owner:"ورثة القندري", address:"نهج المرابطين عدد 41", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:136,  owner:"ورثة المرغني", address:"نهج أحمد غربال عدد 1+3", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:137,  owner:"إسماعيل البلقوطي", address:"نهج القصبة عدد 17", type:"برج من سور المدينة", diagnosis:"برج من سور المدينة العتيقة، تآكل بالحجارة وتشققات", intervention:"ترميم البرج والحفاظ على النمط التقليدي للسور", risk:"Orange", verified:false },
{ id:138,  owner:"—", address:"نهج القصبة زنقة عدد 1", type:"دكان", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:139,  owner:"—", address:"نهج القصبة عدد 59", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:140,  owner:"—", address:"نهج القصبة عدد 61", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:141,  owner:"الجراية", address:"نهج القصبة عدد 69", type:"منزل ميغم", diagnosis:"منزل تقليدي مغلق ومهجور، حالة تدهور عامة", intervention:"رفع الاقتضاض، المحافظة على الحجارة، الحجرة المعمارية", risk:"Orange", verified:false },
{ id:142,  owner:"ملك الدولة", address:"زاوية سيدي حمدان، نهج القصبة عدد 97", type:"زاوية", diagnosis:"معلم ديني تاريخي (زاوية سيدي حمدان)، مغلق ومهجور بسبب توقف النشاط", intervention:"ترميم المعلم وإتمام الأعمال اللازمة لتوفير الاعتمادات", risk:"Orange", verified:false },
{ id:143,  owner:"ورثة حسين الدخلاوي", address:"نهج القصبة زنقة 2 عدد 6", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:144,  owner:"—", address:"نهج القصبة عدد 60+58", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:145,  owner:"—", address:"نهج القصبة عدد 66", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:146,  owner:"—", address:"نهج الشيخ التيجاني عدد 1", type:"منزل ميغم", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:147,  owner:"—", address:"نهج أملكار عدد 7", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:148,  owner:"—", address:"نهج أملكار عدد 9", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:149,  owner:"—", address:"نهج أملكار عدد 15", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:150,  owner:"—", address:"نهج أملكار عدد 17", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:151,  owner:"—", address:"نهج أملكار عدد 19", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:152,  owner:"سالم قريبعة", address:"نهج أملكار عدد 16", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:153,  owner:"—", address:"نهج أملكار عدد 33", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:154,  owner:"رائج طرشونة", address:"نهج أملكار زنقة 66 عدد 2", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:155,  owner:"سعاد عبد اللاوي", address:"نهج أملكار زنقة 66 عدد 11", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:156,  owner:"ورثة السماوي", address:"نهج بن قدور عدد 25+27", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:157,  owner:"—", address:"نهج بن قدور عدد 49", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:158,  owner:"—", address:"نهج سيدي عباس عدد 16", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:159,  owner:"ورثة خديجة دمق", address:"نهج سيدي عباس عدد 13", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:160,  owner:"ورثة محمد المكور", address:"نهج سيدي عباس عدد 15", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:161,  owner:"ورثة مصطفى كمون", address:"نهج سيدي عباس عدد 23", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:162,  owner:"ورثة البيناتي", address:"نهج سيدي عباس عدد 25", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:163,  owner:"عبد الحميد القسطيني", address:"نهج ابن رشد عدد 46", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:164,  owner:"ملك بلدي", address:"نهج ابن رشد عدد 47", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:165,  owner:"علي العش", address:"نهج ابن رشد عدد 49", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:166,  owner:"الصادق البقلوطي", address:"نهج الشيخ التيجاني بودية عدد 8+10", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:167,  owner:"—", address:"نهج الشيخ التيجاني عدد 20", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:168,  owner:"بوراوي البحري", address:"نهج الشيخ التيجاني عدد 22", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:169,  owner:"بوراوي البحري", address:"نهج الشيخ التيجاني عدد 24", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:170,  owner:"سفيان الصغير", address:"نهج الشيخ التيجاني عدد 11", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:171,  owner:"خالدة بن حسانة", address:"نهج الشيخ التيجاني عدد 13", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:172,  owner:"منجية بن طاهر / الطاهر بن عمر", address:"نهج الشيخ التيجاني عدد 28", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:173,  owner:"ورثة الشرفي", address:"نهج الشيخ التيجاني عدد 79", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:174,  owner:"ورثة محمود خروف", address:"نهج الشيخ التيجاني عدد 91", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:175,  owner:"ورثة محمود خروف", address:"نهج الشيخ التيجاني عدد 93", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:176,  owner:"ورثة محمود خروف", address:"نهج الشيخ التيجاني عدد 95", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:177,  owner:"—", address:"نهج الشيخ التيجاني عدد 97", type:"دكان", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:178,  owner:"—", address:"نهج عبد القادر عدد 95", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:179,  owner:"فتحية اللحياني", address:"نهج عبد القادر عدد 109", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:180,  owner:"عبد الرحمان بوزيد", address:"نهج عبد القادر عدد 114", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:181,  owner:"ورثة الميزوري", address:"نهج محمد كمون عدد 10", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:182,  owner:"—", address:"نهج محمد كمون عدد 5", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:183,  owner:"البيادي الرياحي", address:"نهج محمد كمون عدد 13", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:184,  owner:"ورثة منصور مصدق", address:"نهج القصر عدد 11", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:185,  owner:"—", address:"نهج القصر عدد 14", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:186,  owner:"ورثة علي الرقيق", address:"نهج القصر عدد 39", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:187,  owner:"البيادي الحصائري", address:"نهج القصر عدد 45", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:188,  owner:"البرجي", address:"نهج القصر عدد 47", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:189,  owner:"القرقوري", address:"نهج القصر عدد 81", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:190,  owner:"زهرة الشريف", address:"نهج القصر عدد 93", type:"دكان", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:191,  owner:"محمد العش", address:"نهج القصر عدد 95", type:"طابق أول + طابق ثاني", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:192,  owner:"—", address:"نهج القصر عدد 97", type:"طابق أول + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:193,  owner:"—", address:"نهج القصر عدد 78", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:194,  owner:"ورثة أحمد الطريقي", address:"نهج القصر عدد 86", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:195,  owner:"أحمد علو", address:"نهج القصر عدد 115", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:196,  owner:"ورثة الصادق بالأكحل", address:"نهج القصر عدد 139 مكرر", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:197,  owner:"أسعد الياقي", address:"نهج القصر عدد 149", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:198,  owner:"أحمد الترعي", address:"نهج القصر عدد 151", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:199,  owner:"عبد المجيد كمال", address:"نهج القصر عدد 151 مكرر", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:200,  owner:"—", address:"نهج القصر زنقة 3 عدد 1 مكرر", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:201,  owner:"—", address:"نهج القصر زنقة 3 عدد 3", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:202,  owner:"—", address:"نهج القصر زنقة 3 عدد 5", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:203,  owner:"ورثة محمد العبادي", address:"نهج القصر زنقة 4 عدد 1 مكرر", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:204,  owner:"حبيبة بورزة", address:"نهج القصر زنقة 4 عدد 7", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:205,  owner:"ورثة عمر الحبيب", address:"نهج القصر زنقة 4 عدد 2+4", type:"دكان + طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:206,  owner:"—", address:"نهج القصر زنقة 4 عدد 9", type:"منزل ميغم", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:207,  owner:"محمد البيتاتي", address:"نهج القصر زنقة 4 عدد 11", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:208,  owner:"—", address:"نهج القصر زنقة 4 عدد 6", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:209,  owner:"الحنينة", address:"نهج القصر زنقة 4 عدد 12", type:"منزل ميغم", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:210,  owner:"ثمور", address:"نهج القصر زنقة 4 عدد 15", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:211, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:212, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:213, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:214, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:215, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:216, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:217, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:218, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:219, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:220, owner:null, address:null, type:null, diagnosis:null, intervention:null, risk:"Unknown", verified:false, hasData:false, note:"لا يوجد هذا الرقم في الكشف البياني الأصلي (فجوة في الترقيم من 211 إلى 220)." },
{ id:221,  owner:"—", address:"نهج الربيعة زنقة 35 عدد 1-3-5-8-6-4-2/7", type:"طابق أرضي + طابق علوي", diagnosis:"مجموعة من العقارات ميغم بابها مطموس أصبحت ساحة مسيجة، تكدست بداخلها بقايا الأنقاض والأوساخ والقوارض وأصبحت مصبا للفضلات والنفايات الصناعية في اتلاع جدير الاختصاص", intervention:"رفع الأنقاض والفضلات وتنظيف الواجهات الداخلية وترميم الاجهزة الحمائية", risk:"Orange", verified:false },
{ id:222,  owner:"—", address:"نهج تبرورة عدد 50-52", type:"طابق أرضي + طابق علوي", diagnosis:"عقار ميغم بابه مطموس اصبح ساحة مسيجة تكدست بداخلها بقايا انقاض والاوساخ", intervention:"رفع الاقتضاض وتنظيف الفضاء الداخلي وإزالة النخالة", risk:"Orange", verified:false },
{ id:223,  owner:"—", address:"نهج سيدي خليل بن عيسى عدد 73", type:"طابق أرضي", diagnosis:"عقار ميغم بابه مطموس اصبح ساحة مسيجة تكدست بداخلها بقايا انقاض والاوساخ", intervention:"رفع الاقتضاض وتنظيف الفضاء الداخلي وإزالة النخالة", risk:"Orange", verified:false },
{ id:224,  owner:"نزار اللجمي", address:"نهج سيدي خليل بن عيسى عدد 6", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:225,  owner:"ورثة الصادق الوكيل", address:"نهج خير الدين عدد 56", type:"مخزرة", diagnosis:"مخزرة، عقار ميغم", intervention:"رفع الاقتضاض وتنظيف الفضاء الداخلي وإزالة النخالة", risk:"Orange", verified:false },
{ id:226,  owner:"محمد تقي", address:"نهج السور عدد 152-152 مكرر / نهج السماء عدد 1", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:227,  owner:"ورثة محمد ذويب", address:"نهج السماء عدد 11", type:"مخزرة", diagnosis:"مخزرة، عقار ميغم بابه مطموس", intervention:"رفع الاقتضاض وتنظيف الفضاء الداخلي", risk:"Orange", verified:false },
{ id:228,  owner:"—", address:"نهج محمد بوزيد عدد 35 / نهج الحدادين عدد 92", type:"مخزرة", diagnosis:"مخزرة مغلقة بابها مطموس اصبحت ساحة مسيجة ومصبا للقوارض", intervention:"رفع الاقتضاض وتنظيف الفضاء وإزالة النخالة", risk:"Orange", verified:false },
{ id:229,  owner:"—", address:"نهج سيدي سعيد خنفير عدد 5", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:230,  owner:"—", address:"نهج سيدي سعيد خنفير عدد 9", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:231,  owner:"بن عبد الله", address:"نهج سيدي سعيد خنفير عدد 11", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:232,  owner:"خليفة", address:"نهج برج النار عدد 87", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:233,  owner:"—", address:"نهج خير الدين عدد 7", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:234,  owner:"—", address:"نهج خير الدين عدد 9", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:235,  owner:"ملك الدولة (مسجد سيدي البرشاني)", address:"نهج الحميدية عدد 4", type:"مسجد", diagnosis:"معلم ديني (مسجد سيدي البرشاني)، بحاجة إلى صيانة دورية", intervention:"متابعة الصيانة الدورية للمعلم مع المحافظة على الاعتمادات المعمارية", risk:"Orange", verified:false },
{ id:236,  owner:"ملك الدولة (مسجد سيدي علي غلاب)", address:"نهج الحميدية عدد 15", type:"مسجد", diagnosis:"معلم ديني (مسجد سيدي علي غلاب)، بحاجة إلى صيانة دورية", intervention:"متابعة الصيانة الدورية للمعلم", risk:"Orange", verified:false },
{ id:237,  owner:"—", address:"نهج الدريبة عدد 50", type:"حمام السلطان", diagnosis:"حمام تاريخي (حمام السلطان)، معلم عمراني بحالة تستوجب المتابعة", intervention:"ترميم العمل مع الحفاظ على العناصر المعمارية والعروف التاريخية", risk:"Orange", verified:false },
{ id:238,  owner:"عبد الحميد بوعزيز", address:"نهج السور عدد 70", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:239,  owner:"محمد التركي", address:"نهج القصبة عدد 24", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:240,  owner:"حسونة التركي", address:"نهج القصبة عدد 26-28", type:"دكان + طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:241,  owner:"—", address:"نهج القصبة عدد 23", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:242,  owner:"—", address:"نهج باب الجديد العيساوية عدد 68", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:243,  owner:"التوفيق بن منصور", address:"نهج باب الجديد عدد 57", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:244,  owner:"محمد الملولي", address:"نهج بويكر الفقروي عدد 13", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:245,  owner:"—", address:"نهج أملكار زنقة 66 عدد 1+3", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:246,  owner:"—", address:"نهج القصر زنقة 4 عدد 8", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:247,  owner:"ورثة محمد بن جماعة", address:"نهج محمد كمون عدد 24", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:248,  owner:"ملك بلدي", address:"نهج عبد القادر زنقة 30 عدد 10", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:249,  owner:"الحبيب القريحة", address:"نهج سيدي عباس عدد 24", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:250,  owner:"—", address:"نهج أحمد ملاك عدد 32", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:251,  owner:"عبد اللطيف الراتي", address:"نهج أحمد ملاك عدد 34", type:"دكان (مخزن)", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:252,  owner:"علي الحضينة", address:"نهج أحمد ملاك عدد 36", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:253,  owner:"—", address:"نهج أحمد ملاك عدد 21", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:254,  owner:"مراد القندنجي", address:"نهج القصبة عدد 8", type:"دكان + غرفة", diagnosis:"محل تجاري (دكان)، تشققات وتصدعات جزئية بالجدران", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:255,  owner:"ورثة الشعبوني", address:"نهج بويكر القفروي عدد 2", type:"طابق أرضي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:256,  owner:"—", address:"نهج بويكر القفروي عدد 4", type:"طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:257,  owner:"ورثة الدرندي", address:"نهج القصر زنقة 4 عدد 2 مكرر", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },
{ id:258,  owner:"ورثة الجراية", address:"نهج القصر زنقة 4 مكرر عدد 4", type:"طابق أرضي + طابق علوي", diagnosis:"تشققات وتصدعات بالجدران وحالة البناء سيئة", intervention:"ترميم قبل السقوط", risk:"Orange", verified:false },

];

/* عدد العقارات الكلي بالكشف الأصلي (للمرجعية فقط) */
const ATRISK_TOTAL_COUNT = 258;
